# Generated by Django 5.0.7 on 2024-08-12 21:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pages",
            options={
                "ordering": ["order", "title"],
                "verbose_name": "Page",
                "verbose_name_plural": "Pages",
            },
        ),
        migrations.AddField(
            model_name="pages",
            name="order",
            field=models.SmallIntegerField(default=0, verbose_name="Orden"),
        ),
    ]
